name: go-light-framework

services:
  psql:
    build: ./docker/postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - psql_volume:/var/lib/postgresql/data
    networks:
      - app-network

  pgadmin:
    build: ./docker/pgadmin
    profiles: ["dev"]
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "7894:80"
    networks:
      - app-network

  redisinsight:
    build: ./docker/redisinsight
    profiles: ["dev"]
    restart: always
    ports:
      - "5540:5540"
    networks:
      - app-network

  redis:
    build: ./docker/redis
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_volume:/data
    networks:
      - app-network

volumes:
  psql_volume:
  redis_volume:

networks:
  app-network:
    name: go-light-framework
    driver: bridge
